apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: hello
  name: hello-svc
spec:
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    run: hello
  type: LoadBalancer
status:
  loadBalancer: {}
