#values of deployment

hello:
  replicaCount: 3
  image:
    repository: public.ecr.aws/c3w1m1q2/hello_service_adarsh
    tag: latest
  service:
    type: LoadBalancer
    port: 3001

profile:
  replicaCount: 3
  image:
    repository: public.ecr.aws/c3w1m1q2/profile_service_adarsh
    tag: latest
  service:
    type: LoadBalancer
    port: 3002

frontend:
  replicaCount: 3
  image:
    repository: public.ecr.aws/c3w1m1q2/frontend_service_adarsh
    tag: latest
  service:
    type: LoadBalancer
    port: 3000


